// This file was autogenerated on 2022-12-01T11:56:23.682Z.
// DO NOT EDIT THIS FILE.

import type { ThemeOptions } from '@mui/material/styles';

export const rezlynxTheme: ThemeOptions = {
  palette: {
    grey: {
      '100': '#fafcfe',
      '200': '#ECEFF3',
      '250': '#e3e2e9',
      '300': '#C7C6D2',
      '400': '#9a98ae',
      '500': '#5f5e6e',
      '600': '#2f2d43'
    },
    common: {
      black: '#000000',
      white: '#ffffff'
    },
    primary: {
      main: '#31249F',
      hovered: '#221970',
      pressed: '#191353',
      contrastText: '#fff'
    },
    primaryColourPartial: {
      '100': '#EBEAF6',
      '200': '#CBC8E5',
      '300': '#4A3CC3'
    },
    secondary: {
      main: '#bae8be',
      hovered: '#8FBC93',
      pressed: '#6E8C71',
      contrastText: '#31249F'
    },
    secondaryColourPartial: {
      '100': '#effaf0',
      '200': '#dbf5dd',
      '300': '#c9edcc'
    },
    tertiary: {
      main: '#fdba87',
      hovered: '#C9956E',
      pressed: '#9A6D4C',
      contrastText: '#2F2D43'
    },
    tertiaryColourPartial: {
      '100': '#feeee1',
      '200': '#fbddc6',
      '300': '#f9ccaa'
    },
    success: {
      main: '#23DCB2',
      contrastText: '#2F2D43'
    },
    successColourPartial: {
      '100': '#DCF9F3',
      '200': '#abf2e2',
      '300': '#84ECD4'
    },
    info: {
      main: '#075987',
      hovered: '#11435F',
      pressed: '#0C3145',
      contrastText: '#fff'
    },
    infoColourPartial: {
      '100': '#cbdde7',
      '200': '#82acc4',
      '300': '#4483a7'
    },
    warning: {
      main: '#f5f500',
      contrastText: '#2F2D43'
    },
    warningColourPartial: {
      '100': '#fefee2',
      '200': '#fcfcbb',
      '300': '#f8f863'
    },
    error: {
      main: '#A91E43',
      hovered: '#7A1F37',
      pressed: '#57192A',
      contrastText: '#fff'
    },
    errorColourPartial: {
      '100': '#F4D2DB',
      '200': '#E48BA3',
      '300': '#D95477'
    },
    text: {
      primary: '#2f2d43',
      secondary: '#5f5e6e',
      disabled: '#5f5e6e',
      link: '#31249F',
      error: '#A91E43'
    },
    divider: '#C7C6D2',
    background: {
      default: '#ECEFF3'
    },
    buttonTertiary: {
      main: '#fafcfe',
      hovered: 'rgba(47, 45, 67, 0.08)',
      pressed: 'rgba(47, 45, 67, 0.16)',
      contrastText: '#2f2d43'
    },
    ghost: {
      main: '#fafcfe',
      hovered: 'rgba(47, 45, 67, 0.08)',
      pressed: 'rgba(47, 45, 67, 0.16)',
      contrastText: '#2f2d43'
    },
    tagPrimary: {
      contrastText: '#2f2d43',
      main: '#bae8be'
    },
    tagSecondary: {
      contrastText: '#fafcfe',
      main: '#5f5e6e'
    },
    tagTertiary: {
      contrastText: '#2f2d43',
      main: '#e3e2e9'
    },
    tagSubtle: {
      contrastText: '#9a98ae',
      main: '#ECEFF3'
    }
  },
  typography: {
    h1: {
      fontSize: '45px',
      fontWeight: 700,
      fontFamily: 'Syne,Open Sans,-apple-system,BlinkMacSystemFont,Helvetica,Arial,sans-serif',
      lineHeight: '56px',
      letterSpacing: 0
    },
    h2: {
      fontSize: '31px',
      fontWeight: 700,
      fontFamily: '"DM Sans",Open Sans,-apple-system,BlinkMacSystemFont,Helvetica,Arial,sans-serif',
      letterSpacing: -0.62,
      lineHeight: '48px'
    },
    h3: {
      fontSize: '26px',
      fontWeight: 700,
      fontFamily: '"DM Sans",Open Sans,-apple-system,BlinkMacSystemFont,Helvetica,Arial,sans-serif',
      lineHeight: '48px',
      letterSpacing: -0.52
    },
    h4: {
      fontSize: '22px',
      fontWeight: 700,
      fontFamily: '"DM Sans",Open Sans,-apple-system,BlinkMacSystemFont,Helvetica,Arial,sans-serif',
      lineHeight: '32px',
      letterSpacing: 0.44
    },
    h4Regular: {
      fontSize: '22px',
      fontWeight: 400,
      fontFamily: '"DM Sans",Open Sans,-apple-system,BlinkMacSystemFont,Helvetica,Arial,sans-serif',
      lineHeight: '28px',
      letterSpacing: '-0.02em'
    },
    bodyLarge: {
      fontSize: '18px',
      fontWeight: 400,
      fontFamily: '"DM Sans",Open Sans,-apple-system,BlinkMacSystemFont,Helvetica,Arial,sans-serif',
      lineHeight: '24px',
      letterSpacing: 0
    },
    bodyLargeBold: {
      fontSize: '18px',
      fontWeight: 700,
      fontFamily: '"DM Sans",Open Sans,-apple-system,BlinkMacSystemFont,Helvetica,Arial,sans-serif',
      lineHeight: '24px',
      letterSpacing: 0
    },
    body1: {
      fontSize: '16px',
      fontWeight: 400,
      fontFamily: '"DM Sans",Open Sans,-apple-system,BlinkMacSystemFont,Helvetica,Arial,sans-serif',
      lineHeight: '24px',
      letterSpacing: 0
    },
    bodyBold: {
      fontSize: '16px',
      fontWeight: 700,
      fontFamily: '"DM Sans",Open Sans,-apple-system,BlinkMacSystemFont,Helvetica,Arial,sans-serif',
      lineHeight: '24px',
      letterSpacing: 0
    },
    bodySmall: {
      fontSize: '14px',
      fontWeight: 400,
      fontFamily: '"DM Sans",Open Sans,-apple-system,BlinkMacSystemFont,Helvetica,Arial,sans-serif',
      lineHeight: '20px',
      letterSpacing: 0
    },
    bodySmallBold: {
      fontSize: '14px',
      fontWeight: 700,
      fontFamily: '"DM Sans",Open Sans,-apple-system,BlinkMacSystemFont,Helvetica,Arial,sans-serif',
      lineHeight: '20px',
      letterSpacing: 0
    },
    tagLarge: {
      fontSize: '14px',
      fontWeight: 500,
      fontFamily: '"DM Sans",Open Sans,-apple-system,BlinkMacSystemFont,Helvetica,Arial,sans-serif',
      lineHeight: '16px',
      letterSpacing: 0
    },
    tagDefault: {
      fontSize: '12px',
      fontWeight: 400,
      fontFamily: '"DM Sans",Open Sans,-apple-system,BlinkMacSystemFont,Helvetica,Arial,sans-serif',
      lineHeight: '16px',
      letterSpacing: 0
    },
    tagSmall: {
      fontSize: '11px',
      fontWeight: 500,
      fontFamily: '"DM Sans",Open Sans,-apple-system,BlinkMacSystemFont,Helvetica,Arial,sans-serif',
      lineHeight: '12px',
      letterSpacing: '0.02em',
      textTransform: 'uppercase'
    },
    emphasisLarge: {
      fontSize: '16px',
      fontWeight: 500,
      fontFamily: '"DM Sans",Open Sans,-apple-system,BlinkMacSystemFont,Helvetica,Arial,sans-serif',
      lineHeight: '24px',
      letterSpacing: '0.02em',
      textTransform: 'uppercase'
    },
    emphasisDefault: {
      fontSize: '14px',
      fontWeight: 500,
      fontFamily: '"DM Sans",Open Sans,-apple-system,BlinkMacSystemFont,Helvetica,Arial,sans-serif',
      lineHeight: '20px',
      letterSpacing: 0,
      textTransform: 'uppercase'
    },
    emphasisSmall: {
      fontSize: '12px',
      fontWeight: 700,
      fontFamily: '"DM Sans",Open Sans,-apple-system,BlinkMacSystemFont,Helvetica,Arial,sans-serif',
      lineHeight: '16px',
      letterSpacing: '0.04em',
      textTransform: 'uppercase'
    },
    navigation: {
      fontSize: '16px',
      fontWeight: 400,
      fontFamily: '"DM Sans",Open Sans,-apple-system,BlinkMacSystemFont,Helvetica,Arial,sans-serif',
      lineHeight: '24px',
      letterSpacing: 0
    },
    overlineSmall: {
      fontSize: '12px',
      fontWeight: 400,
      fontFamily: '"DM Sans",Open Sans,-apple-system,BlinkMacSystemFont,Helvetica,Arial,sans-serif',
      lineHeight: '24px',
      letterSpacing: '0.02em',
      textTransform: 'uppercase'
    },
    overlineDefault: {
      fontSize: '14px',
      fontWeight: 400,
      fontFamily: '"DM Sans",Open Sans,-apple-system,BlinkMacSystemFont,Helvetica,Arial,sans-serif',
      lineHeight: '24px',
      letterSpacing: '0.02em',
      textTransform: 'uppercase'
    },
    htmlFontSize: 12,
    fontFamily: '"DM Sans",Open Sans,-apple-system,BlinkMacSystemFont,Helvetica,Arial,sans-serif'
  },
  components: {
    MuiMenuItem: {
      styleOverrides: {
        root: {
          padding: '4px 8px',
          borderRadius: '4px'
        }
      }
    },
    MuiPaper: {
      styleOverrides: {
        root: {
          boxShadow: 'initial'
        }
      }
    },
    MuiMenu: {
      styleOverrides: {
        list: {
          padding: '16px',
          minWidth: '240px',
          boxSizing: 'border-box'
        },
        paper: {
          filter: 'drop-shadow(0px 0px 8px rgba(0, 0, 0, 0.1))'
        },
        root: {
          '.MuiPaper-root': {
            borderRadius: '8px'
          },
          '&.MuiMenu-dark': {
            '& .MuiMenuItem-root': {
              '&:hover': {
                background: 'none',
                backgroundColor: 'rgba(255, 255, 255, 0.08)'
              },
              '&:focus': {
                backgroundColor: 'rgba(255, 255, 255, 0.16)'
              }
            },
            '& .MuiPaper-root': {
              color: '#fafcfe',
              background: '#2f2d43'
            }
          }
        }
      }
    },
    MuiCard: {
      styleOverrides: {
        root: {
          fontSize: 14,
          fontFamily: 'DM Sans',
          fontWeight: 400,
          letterSpacing: 0,
          lineHeight: '20px'
        }
      }
    },
    MuiIconButton: {
      styleOverrides: {
        root: {
          boxShadow: '0px 0px 8px rgba(0, 0, 0, 0.1)',
          backgroundImage: 'none',
          borderRadius: '50%',
          '& .MuiTouchRipple-ripple span': {
            borderRadius: 'inherit'
          }
        },
        sizeLarge: {
          width: '48px',
          height: '48px',
          padding: '12px'
        },
        sizeMedium: {
          width: '40px',
          height: '40px',
          padding: '8px'
        },
        sizeSmall: {
          width: '32px',
          height: '32px',
          padding: '8px'
        }
      },
      variants: [
        {
          props: {
            color: 'primary'
          },
          style: {
            color: '#31249F',
            backgroundColor: '#ffffff',
            '&:hover': {
              backgroundColor: '#EBEAF6'
            },
            '& .MuiTouchRipple-ripple span,&:active': {
              backgroundColor: '#CBC8E5'
            }
          }
        }
      ]
    },
    MuiIcon: {
      styleOverrides: {
        root: {
          fontSize: 'inherit'
        }
      }
    },
    MuiSwitch: {
      styleOverrides: {
        root: {
          width: 'auto',
          height: 'auto',
          padding: 0,
          zIndex: 1,
          '&:after, &:before': {
            width: '34px',
            height: '20px',
            borderRadius: '32px',
            position: 'absolute',
            content: '""'
          },
          '.MuiSwitch-sizeSmall&:after, .MuiSwitch-sizeSmall&:before': {
            width: '26px',
            height: '16px'
          },
          '&:after': {
            zIndex: 2,
            boxShadow: 'inset 0px 2px 2px rgba(0, 0, 0, 0.1)'
          },
          '&:before': {
            zIndex: 0,
            backgroundColor: '#ffffff'
          }
        },
        input: {
          zIndex: 'inherit',
          width: '220%',
          height: '132%',
          top: '-3px',
          transform: 'translateX(14px)',
          '.Mui-checked&': {
            transform: 'translateX(0)'
          }
        },
        switchBase: {
          zIndex: 3,
          padding: 0,
          margin: 2,
          '&.Mui-checked': {
            transform: 'translateX(14px)'
          },
          '.MuiSwitch-sizeSmall &': {
            margin: '-2px'
          },
          '.MuiSwitch-root.MuiSwitch-sizeSmall &.Mui-checked': {
            transform: 'translateX(10px)'
          },
          '&:hover': {
            backgroundColor: 'transparent'
          }
        },
        track: {
          zIndex: 'inherit',
          width: '34px',
          height: '20px',
          margin: 0,
          borderRadius: '32px',
          transition: 'background-color .3s ease, opacity .3s ease',
          '.MuiSwitch-switchBase:not(.Mui-checked) + &': {
            opacity: 1,
            backgroundColor: '#ECEFF3'
          },
          '.MuiSwitch-switchBase:hover:not(.Mui-checked) + &': {
            opacity: 1,
            backgroundColor: '#e3e2e9'
          },
          '.MuiSwitch-switchBase.Mui-disabled:not(.Mui-checked) + &': {
            opacity: 1,
            backgroundColor: '#C7C6D2'
          },
          '.MuiButtonBase-root.MuiSwitch-switchBase + .MuiSwitch-track&': {
            opacity: 0.86
          },
          '.MuiSwitch-switchBase.Mui-checked:hover + &': {
            opacity: 1
          },
          '.MuiSwitch-switchBase.Mui-disabled.Mui-checked + &': {
            opacity: 0.25
          },
          '.MuiSwitch-sizeSmall &': {
            width: '26px',
            height: '16px'
          }
        },
        thumb: {
          boxSizing: 'border-box',
          borderRadius: '50%',
          boxShadow: '0px 2px 4px rgba(0, 0, 0, 0.05)',
          width: '16px',
          height: '16px',
          border: '2px transparent',
          color: '#ffffff',
          '.Mui-disabled:not(.Mui-checked) &': {
            color: '#e3e2e9'
          },
          '.MuiSwitch-sizeSmall .MuiSwitch-thumb&': {
            width: '12px',
            height: '12px'
          }
        }
      }
    },
    MuiButton: {
      variants: [
        {
          props: {
            color: 'buttonTertiary',
            variant: 'contained'
          },
          style: {
            color: '#5f5e6e',
            backgroundColor: '#ECEFF3',
            ':hover': {
              backgroundColor: '#e3e2e9'
            },
            ':focus': {
              backgroundColor: '#C7C6D2'
            }
          }
        },
        {
          props: {
            color: 'buttonTertiary',
            variant: 'outlined'
          },
          style: {
            color: '#ECEFF3',
            border: '1px solid #ECEFF3',
            ':hover': {
              backgroundColor: 'rgba(255, 255, 255, 0.08)'
            },
            ':focus': {
              backgroundColor: 'rgba(255, 255, 255, 0.16)'
            }
          }
        },
        {
          props: {
            color: 'buttonTertiary',
            variant: 'text'
          },
          style: {
            color: '#ECEFF3',
            ':hover': {
              backgroundColor: 'rgba(255, 255, 255, 0.08)'
            },
            ':focus': {
              backgroundColor: 'rgba(255, 255, 255, 0.16)'
            }
          }
        }
      ],
      styleOverrides: {
        root: {
          fontFamily:
            '"DM Sans",Open Sans,-apple-system,BlinkMacSystemFont,Helvetica,Arial,sans-serif',
          fontWeight: 500,
          fontSize: '16px',
          textTransform: 'capitalize',
          letterSpacing: -0.32,
          lineHeight: '24px',
          boxShadow: 'none',
          backgroundImage: 'none',
          borderRadius: '8px',
          ':hover': {
            boxShadow: 'none'
          },
          '&.MuiButton-iconOnly, &.MuiButton-avatar': {
            minWidth: 0
          },
          '& .MuiTouchRipple-ripple span': {
            borderRadius: 'inherit'
          },
          '&.MuiButton-selected': {
            backgroundColor: 'rgba(255, 255, 255, 0.16)'
          },
          '& .MuiButton-avatar': {
            borderRadius: '8px'
          }
        },
        sizeLarge: {
          padding: '12px 16px',
          '&.MuiButton-iconOnly': {
            padding: '12px'
          },
          '&.MuiButton-avatar': {
            padding: '6px',
            '.MuiBadge-badge': {
              top: '13%',
              right: '13%'
            }
          }
        },
        sizeMedium: {
          padding: '8px 12px',
          '&.MuiButton-iconOnly': {
            padding: '8px'
          }
        },
        sizeSmall: {
          padding: '4px 8px',
          fontSize: '14px',
          '&.MuiButton-iconOnly': {
            padding: '4px'
          }
        },
        outlined: {
          border: '1px solid undefined',
          '& :hover': {}
        },
        text: {
          '&:hover': {
            backgroundColor: 'rgba(47, 45, 67, 0.08)'
          }
        }
      }
    },
    MuiChip: {
      variants: [
        {
          props: {
            variant: 'tag'
          },
          style: {
            fontSize: '11px',
            fontWeight: 500,
            fontFamily:
              '"DM Sans",Open Sans,-apple-system,BlinkMacSystemFont,Helvetica,Arial,sans-serif',
            lineHeight: '12px',
            letterSpacing: '0.02em',
            textTransform: 'uppercase',
            borderRadius: '4px',
            height: 'auto'
          }
        },
        {
          props: {
            variant: 'tag',
            size: 'small'
          },
          style: {
            padding: '2px 8px'
          }
        },
        {
          props: {
            variant: 'tag',
            size: 'medium'
          },
          style: {
            padding: '4px 8px'
          }
        },
        {
          props: {
            variant: 'outlined',
            size: 'medium'
          },
          style: {
            padding: '4px 12px'
          }
        },
        {
          props: {
            variant: 'outlined',
            color: 'default',
            clickable: true
          },
          style: {
            '&:hover, &.MuiChip-selected:hover': {
              background: '#CBC8E5',
              color: '#31249F',
              borderColor: '#4A3CC3'
            },
            '&:hover .MuiChip-deleteIcon, &.MuiChip-selected:hover .MuiChip-deleteIcon': {
              color: '#31249F'
            }
          }
        },
        {
          props: {
            variant: 'outlined',
            color: 'default'
          },
          style: {
            color: '#5f5e6e',
            background: '#ffffff',
            border: '1px solid #C7C6D2',
            '&.MuiChip-selected': {
              background: '#EBEAF6',
              borderColor: '#4A3CC3',
              color: '#31249F'
            }
          }
        }
      ],
      styleOverrides: {
        root: {
          fontSize: '14px',
          fontWeight: 400,
          fontFamily:
            '"DM Sans",Open Sans,-apple-system,BlinkMacSystemFont,Helvetica,Arial,sans-serif',
          lineHeight: '20px',
          letterSpacing: 0,
          boxSizing: 'border-box',
          borderRadius: '8px',
          height: 'auto'
        },
        icon: {
          margin: 0,
          marginLeft: '-4px',
          paddingRight: '2px',
          fontSize: '18px',
          color: '#2f2d43'
        },
        deleteIcon: {
          margin: 0,
          marginRight: '-4px',
          paddingLeft: '4px',
          fontSize: 'inherit',
          color: 'inherit',
          '&:hover': {
            color: 'inherit'
          }
        },
        label: {
          padding: 0
        }
      }
    },
    MuiTooltip: {
      styleOverrides: {
        arrow: {
          '&::before': {
            backgroundColor: '#fafcfe',
            borderColor: '#fafcfe'
          },
          '&.MuiTooltip-prominent': {
            '&::before': {
              backgroundColor: '#2f2d43',
              borderColor: '#2f2d43'
            }
          },
          '&.MuiTooltip-soft': {
            '&::before': {
              backgroundColor: '#EBEAF6',
              color: '#EBEAF6',
              borderColor: '#EBEAF6'
            }
          }
        },
        tooltip: {
          fontFamily:
            '"DM Sans",Open Sans,-apple-system,BlinkMacSystemFont,Helvetica,Arial,sans-serif',
          fontWeight: 400,
          fontSize: '12px',
          lineHeight: '16px',
          padding: '4px 8px',
          color: '#2f2d43',
          backgroundColor: '#fafcfe',
          borderRadius: '4px',
          filter: 'drop-shadow(0px 2px 4px rgba(0, 0, 0, 0.05))',
          '&.MuiTooltip-prominent': {
            backgroundColor: '#2f2d43',
            color: '#fafcfe'
          },
          '&.MuiTooltip-soft': {
            color: '#31249F',
            backgroundColor: '#EBEAF6'
          }
        }
      }
    },
    MuiInputLabel: {
      styleOverrides: {
        root: {
          color: '#5f5e6e',
          fontSize: '14px',
          lineHeight: '16px',
          top: '4px'
        },
        shrink: {
          '&.MuiInputLabel-outlined': {
            fontSize: '12px',
            left: '-10px',
            top: '-12px',
            transform: 'translate(14px, -9px) scale(1)'
          }
        }
      }
    },
    MuiTextField: {
      styleOverrides: {
        root: {
          '& .Mui-focused': {
            background: '#ffffff'
          },
          '& .Mui-focused fieldset': {
            borderColor: '#31249F',
            boxShadow: '0px 0px 0px 2px rgba(49, 36, 159, 0.25)'
          },
          '& .MuiInputAdornment-positionStart': {
            paddingLeft: '16px'
          },
          '& .MuiInputAdornment-positionEnd': {
            paddingRight: '16px'
          }
        }
      }
    },
    MuiOutlinedInput: {
      styleOverrides: {
        root: {
          boxShadow: 'inset 0px 2px 2px rgba(0, 0, 0, 0.1)',
          borderRadius: '8px',
          color: '#2f2d43',
          background: '#fafcfe',
          padding: '2px 0',
          ':hover': {
            '.MuiOutlinedInput-notchedOutline': {
              borderColor: '#C7C6D2'
            }
          },
          '&.Mui-focused': {
            backgroundColor: '#fafcfe',
            '.MuiOutlinedInput-notchedOutline': {
              borderWidth: '1px',
              borderColor: '#4A3CC3'
            }
          },
          '&.Mui-focused:hover': {
            '.MuiOutlinedInput-notchedOutline': {
              borderColor: '#4A3CC3'
            }
          },
          '&.Mui-disabled': {
            backgroundColor: '#e3e2e9',
            color: '#9a98ae',
            '.MuiOutlinedInput-notchedOutline': {
              borderColor: '#e3e2e9'
            }
          },
          '.MuiInputAdornment-root': {
            'svg path': {
              fill: '#9a98ae'
            }
          }
        },
        input: {
          fontSize: '14px',
          fontWeight: 400,
          lineHeight: '16px',
          maxHeight: '40px',
          '&::placeholder': {
            color: '#C7C6D2',
            opacity: 1
          },
          '&.Mui-disabled': {
            '-webkit-text-fill-color': 'unset'
          }
        },
        multiline: {
          padding: '12px 16px'
        },
        notchedOutline: {
          borderWidth: '1px',
          borderRadius: '8px',
          borderColor: '#e3e2e9',
          '& legend span:not(.notranslate)': {
            display: 'none'
          }
        }
      }
    },
    MuiCheckbox: {
      styleOverrides: {
        root: {
          width: '20px',
          height: '20px',
          borderRadius: '5px',
          backgroundColor: '#ECEFF3',
          padding: 0,
          margin: 0,
          boxShadow: 'inset 0px 2px 2px rgba(0, 0, 0, 0.1)',
          '&:hover': {
            backgroundColor: '#e3e2e9'
          },
          '&.Mui-focusVisible': {
            backgroundColor: '#e3e2e9',
            opacity: 0.8
          },
          '&.Mui-required': {
            boxShadow: '0px 0px 0px 2px rgba(202, 27, 87, 0.2)',
            border: '1px solid #D95477'
          }
        },
        colorPrimary: {
          '&.Mui-checked': {
            color: '#ffffff',
            backgroundColor: '#4A3CC3',
            '&:hover': {
              backgroundColor: '#31249F'
            }
          }
        }
      }
    },
    MuiAvatar: {
      styleOverrides: {
        root: {
          position: 'relative',
          boxSizing: 'border-box',
          '&.mui-avatar-extraLarge': {
            padding: '16px',
            width: '52px',
            height: '52px'
          },
          '&.mui-avatar-large': {
            padding: '8px',
            width: '36px',
            height: '36px'
          },
          '&.mui-avatar-small': {
            padding: '6px',
            width: '32px',
            height: '32px'
          },
          '&.mui-avatar-extraSmall': {
            padding: '4px',
            width: '24px',
            height: '24px'
          }
        },
        img: {
          position: 'absolute'
        }
      },
      variants: [
        {
          props: {
            variant: 'rounded'
          },
          style: {
            '&.mui-avatar-extraLarge': {
              borderRadius: '12px'
            },
            '&.mui-avatar-large': {
              borderRadius: '8px'
            },
            '&.mui-avatar-small': {
              borderRadius: '8px'
            },
            '&.mui-avatar-extraSmall': {
              borderRadius: '4px'
            }
          }
        }
      ]
    },
    MuiBadge: {
      styleOverrides: {
        anchorOriginTopRight: {
          top: '4%',
          right: '4%'
        },
        badge: {
          minWidth: '8px',
          height: '8px',
          '&.MuiBadge-medium': {
            minWidth: '16px',
            height: '16px',
            padding: '0 4px'
          },
          '&.MuiBadge-large': {
            minWidth: '20px',
            height: '20px',
            padding: '0 6px'
          }
        }
      }
    },
    MuiSkeleton: {
      styleOverrides: {
        root: {
          borderRadius: '4px',
          backgroundColor: 'rgba(47, 45, 67, 0.16)',
          '&.MuiSkeleton-dark': {
            backgroundColor: 'rgba(255, 255, 255, 0.16)'
          }
        }
      }
    }
  }
};
